### ISSUE TITLE
Getting error after creating the release in Exercise 3: Deploy resources using Terraform (IaC) in Azure CD pipeline

### ISSUE THREAD

**Issue by GhumanNavneet** [microsoft/azuredevopslabs#395]
The configuration file here is webapp.tf due which we are getting this issue.
The "backend" is the interface that Terraform uses to store state, perform operations, etc. If this message is showing up, it means that the Terraform configuration you're using is using a custom configuration for the Terraform backend.
Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1

**Comment by GhumanNavneet** [comment]
any update on this??

**Comment by robnhls** [comment]
If you adjust the webapp.tf file in the terraform directory to be the following, it should work.  The features{} lines were added and the provider "azurerm" section was also added.

```
terraform {
required_version = ">= 0.11"

backend "azurerm" {
storage_account_name = "__terraformstorageaccount__"
container_name = "terraform"
key = "terraform.tfstate"
access_key ="__storagekey__"
features{}
}
}
provider "azurerm" {
features {}
}

resource "azurerm_resource_group" "dev" {
  name     = "PULTerraform"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "dev" {
  name                = "__appserviceplan__"
  location            = "${azurerm_resource_group.dev.location}"
  resource_group_name = "${azurerm_resource_group.dev.name}"

  sku {
    tier = "Free"
    size = "F1"
  }
}

resource "azurerm_app_service" "dev" {
  name                = "__appservicename__"
  location            = "${azurerm_resource_group.dev.location}"
  resource_group_name = "${azurerm_resource_group.dev.name}"
  app_service_plan_id = "${azurerm_app_service_plan.dev.id}"
}
```

**Comment by sriramdasbalaji** [comment]
Hi @GhumanNavneet ,

We have fixed the issue in Terraform file. 

@robnhls  Thanks for your help. We have added the features block in the terraform file of the template.

Thanks

**Comment by kapil12345** [comment]
Hey @robnhls used above file which have mentioned above still getting same error. 2020-04-29T20:58:26.5533237Z ##[error]Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1.

**Comment by akhilbisht** [comment]
Just make sure that the container name is set correctly in task "Terraform : init" 

e.g: terraform

**Comment by kanan2u** [comment]
I have set the container name as "terraform" in task "Terraform : init". I am still getting this issue. Can anyone suggest?

**Comment by Pankajazlearn** [comment]
I am getting the same error even after adding the features block

**Comment by AlanJ97** [comment]
Any updates? I'm getting this error and I can´t solve it. I copied and pasted the code from @robfoulkrod , but I'm still getting "
Error: The process 'C:\hostedtoolcache\windows\terraform\0.12.3\x64\terraform.exe' failed with exit code 1"?

**Comment by rajnokialab** [comment]
same issue for me..

**Comment by AlanJ97** [comment]
@rajnokialab I solved like this:

In the task "Replace Tokens in terraform file" I changed to the next Token Pattern: 

![image](https://user-images.githubusercontent.com/51300800/165750851-66420a7e-e269-4f7d-a96a-e372dcda6671.png)

**Comment by rahul-santosh7** [comment]
> same issue for me..

same issue for mee too
